### ISSUE TITLE
Pubg LibUE4 Dump

### ISSUE THREAD

**Issue by H4X4U** [BryanGIG/LibDumper#4]
**Does This can dump LibUe4 From Pubg ?,**
If Yes, I Have Non Rooted Phone Can U Tell Me What Process I Have To Follow 🙂,
Btw Thanks For Great Release 😍

**Comment by BryanGIG** [comment]
Since [LibDumper 3.3](https://github.com/BryanGIG/LibDumper/releases/tag/v3.3), I already delete options for dumping libUE4.so from memory.
But if you want to use it to dump libUE4.so, you can follow these steps:
- follow steps 1-3, [here](https://github.com/BryanGIG/LibDumper#usage)
- uncheck dump global-metadata
- put "libUE4.so" in edit text lib name
- click "Dump"

**Comment by H4X4U** [comment]
Ok I Will Try That,
Thanks for replying 🤗
